// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLWpSkkQTXoUeN_WXIJLsGEgJKAB-pL_w',
    appId: '1:372082273349:web:15dd088a7fe1be1085472c',
    messagingSenderId: '372082273349',
    projectId: 'breathinapp-1d029',
    authDomain: 'breathinapp-1d029.firebaseapp.com',
    storageBucket: 'breathinapp-1d029.firebasestorage.app',
    measurementId: "G-0EKRFDHCEK",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCscegZxVNbopjEnTrmBYF7u0k-y0s5C6A',
    appId: '1:372082273349:android:76abe2e000d459a985472c',
    messagingSenderId: '372082273349',
    projectId: 'breathinapp-1d029',
    storageBucket: 'breathinapp-1d029.firebasestorage.app',
  );
}
